spring.application.name=Spring Boot Actuator Monitoring

server.port=8081


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.db.enabled=true


spring.datasource.url=jdbc:mysql://localhost:3306/actuator_monitoring
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true