server.port=8081

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Informations sur l'application pour l'endpoint /actuator/info
info.app.name=Spring Boot Actuator Monitoring
info.app.description=Application de démonstration pour Spring Boot Actuator avec indicateurs personnalisés
info.app.version=1.0.0
info.app.encoding=@project.build.sourceEncoding@
info.app.java.version=@java.version@
management.prometheus.metrics.export.enabled=true